apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "thunderhelm.fullname" . }}-secrets
  labels:
    {{- include "thunderhelm.labels" . | nindent 4 }}
stringData:
  {{- range $k, $v := .Values.env.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
