[package]
name = "cerebros_numerics"
version = "0.1.0"
edition = "2021"

[lib]
name = "cerebros_numerics"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
rustler = { version = "0.36" }
half = "2"
rayon = "1"
