{{- if and .Values.livebook.enabled .Values.livebook.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "thunderhelm.fullname" . }}-livebook
  labels:
    {{- include "thunderhelm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.livebook.persistence.size | default "5Gi" }}
  {{- if .Values.livebook.persistence.storageClass }}
  storageClassName: {{ .Values.livebook.persistence.storageClass }}
  {{- end }}
{{- end }}
