apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thunderhelm.fullname" . }}-web
  labels:
    {{- include "thunderhelm.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "thunderhelm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "thunderhelm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
        {{- with .Values.web.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ default (include "thunderhelm.fullname" .) .Values.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "thunderhelm.fullname" . }}-env
            - secretRef:
                name: {{ include "thunderhelm.fullname" . }}-secrets
          env:
            {{- range $k, $v := .Values.web.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.web.service.port }}
          {{- with .Values.probes.web.liveness }}
          livenessProbe:
            httpGet:
              path: {{ .path | default "/health" | quote }}
              port: http
            initialDelaySeconds: {{ .initialDelaySeconds | default 20 }}
            periodSeconds: {{ .periodSeconds | default 10 }}
          {{- end }}
          {{- with $.Values.probes.web.readiness }}
          readinessProbe:
            httpGet:
              path: {{ .path | default "/" | quote }}
              port: http
            initialDelaySeconds: {{ .initialDelaySeconds | default 10 }}
            periodSeconds: {{ .periodSeconds | default 10 }}
          {{- end }}
          {{- with $.Values.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
